config/routes.rb
Staritup::Application.routes.draw do

  resources :backers

  resources :terms

  resources :policies

  resources :projects

  resources :guidelines

  resources :startprojects

  resources :answers

  resources :questions

  resources :wizard_steps

  resources :businessplans

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  resources :welcomes

  resources :users

  resources :categories

   root :to => 'welcomes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :featured, :question_id, :user_id

  belongs_to :question
  belongs_to :user

end

app/models/backer.rb
class Backer < ActiveRecord::Base
  attr_accessible :confirmed_at, :finished, :project_id, :user_id, :value, :newsomme

  belongs_to :user
  belongs_to :project
end

app/models/businessplan.rb
class Businessplan < ActiveRecord::Base
  attr_accessible :order, :status, :wizard_answer, :wizard_question, :wizard_step_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :parent, :slug

  	has_many :questions, :foreign_key => :category_id, dependent: :destroy
	has_many :projects, :foreign_key => :category_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug


	has_many :projects, :foreign_key => :location_id, :dependent => :destroy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :challenges, :description, :location_id, :miniature, :category_id, :slug, :title, :video, :user_id, :needs, :somme, :how_know, :facebook_link, :twitter_link, :accepted, :featured, :rejected_for

  belongs_to :user
  belongs_to :location
  belongs_to :category


  has_many :backers, :foreign_key => :project_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :miniature, MiniatureUploader


end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :featured, :is_solved, :question, :slug, :status, :subject, :user_id

  belongs_to :category
  belongs_to :user

  has_many :answers, :foreign_key => :question_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :subject, use: :slugged

end

app/models/startproject.rb
class Startproject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/term.rb
class Term < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :avatar, :biography, :birthday, :birthmonth, :birthyear, :cid, :country_id, :is_coach, :name, :phone, :slug, :state_id, :town, :username, :website, :provider, :uid

  has_many :questions, :foreign_key => :user_id, :dependent => :destroy
  has_many :answers, :foreign_key => :user_id, :dependent => :destroy
  has_many :projects, :foreign_key => :user_id, :dependent => :destroy
  has_many :backers, :foreign_key => :user_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :avatar, AvatarUploader

  acts_as_taggable
  acts_as_taggable_on :skills, :interests


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end



  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end



  
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/wizard_step.rb
class WizardStep < ActiveRecord::Base
  attr_accessible :name, :order

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  # GET /welcomes
  # GET /welcomes.json
  def index
    #@welcomes = Welcome.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @welcomes }
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/backers_helper.rb
module BackersHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_connect_module.html.erb
<% unless user_signed_in? %>
<div id="connectmodule">
	<div class="insideconnect">
		<div class="normallogins">
			<div class="big">
				Découvrez d'énorme projets avec vos amis, réalisez vos ambitions!
			</div>
			Vous pouvez soit vous <%= link_to 'enregistrer', register_path() %> soit vous <%= link_to 'connecter', login_path() %> pour en profiter plus.
		</div>
		<div class="sociallogins">
			<%= link_to 'Se Connecter Avec Facebook', "", :class => "facebook" %>
		</div>
	</div>
</div>
<% end %>

app/views/welcomes/_explanation_module.html.erb
<div id="explanationmodule">
	<div class="insideexplanation">
		<div class="big">
			D'où viennent nos reponses?
		</div>
		<div class="text">
			Chaque personne ici présente, a un jour été confronté au problème auquel vous faites face, ou un problème similaire, et collabore avec cette plateforme pour en faire la plus grande base de données nationale de solution. Vous souhaitez en savoir plus sur comment les projets naissent? <%= link_to "Enregistrer vous", register_path() %> et commencez à accumuler la connaissance ici.
		</div>
	</div>
</div>

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/_hero_module.html.erb
<div id="heromodule">
	<div id="hero" class="hero slide">
	  <!-- Carousel items -->
	  <div class="carousel-inner">
	    <div class="active item"><%= image_tag "backgrounds/hero1.jpg" %> </div>
	    <div class="item"><%= image_tag "backgrounds/hero3.jpg" %> </div>
	    <div class="item"><%= image_tag "backgrounds/hero2.jpg" %> </div>
	  </div>
	  <!-- Carousel nav -->
	  <a class="carousel-control left" href="#hero" data-slide="prev">&lsaquo;</a>
	  <a class="carousel-control right" href="#hero" data-slide="next">&rsaquo;</a>
	</div>
</div>

app/views/welcomes/_last_projects_module.html.erb
<div id="lastprojectsmodule">
	<div class="header">
		<div class="left">
			<%= image_tag "icons/startup.png" %> Derniers Projets Ajoutés
		</div>

		<div class="right">
			<%= link_to "Découvrir le tout", projects_path(	) %>
		</div>
	</div>

	<div class="projectsbox">

		<% Project.order("created_at").last(4).each do |project| %>
		<div class="projectbox">
			<div class="project">
				<div class="image">
					<%= image_tag project.miniature.to_s %>
				</div>

				<div class="title">
					<%= link_to project.title, project_path(project) %>
				</div>

				<div class="founder">
					par <%= link_to project.user.name, user_path(project.user) %>
				</div>
				
				<div class="abstract">
					<%= project.abstract %>
				</div>

				<div class="location">
					<%= image_tag "icons/location.png" %><%= project.location.name %>, Tunisie
				</div>
				
			</div>
			<div class="projectstats">
				<div class="progressbar">
					&nbsp;

					<div class="fill">
						
					</div>
				</div>

				<div class="percentages">
					<div class="percentage">
						<div class="number">
							92%
						</div>

						<div class="label">
							Investis
						</div>
					</div>
					<div class="percentage">
						<div class="number">
							<%= project.somme %>
						</div>

						<div class="label">
							Dinars
						</div>
					</div>
				</div>
			</div>
			
		</div>
		<% end %>

	</div>
</div>

app/views/welcomes/_last_questions_module.html.erb
<% unless Question.order("created_at").last.nil? %>


<div id="introquestionsmodule">
	<div class="header">
		<div class="left">
			<%= image_tag "icons/comments.png" %> Dernières Questions
		</div>

		<div class="right">
			<%= link_to "Découvrir le tout", questions_path(	) %>
		</div>
	</div>

  <div class="lastone">
    <strong><%= Question.last.subject %></strong></br>
    <%= raw(Question.last.question) %>
  </div>
  <div class="listcategories">
    <ul>
      <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<%= render "welcomes/hero_module" %>


<%= render "welcomes/last_questions_module" %>


<%= render "welcomes/connect_module.html.erb" %>


<%= render "welcomes/last_projects_module" %>


<%= render "welcomes/explanation_module" %>

app/views/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>