config/routes.rb
Staritup::Application.routes.draw do

  resources :backers

  resources :terms

  resources :policies

  resources :projects

  resources :guidelines

  resources :startprojects

  resources :answers

  resources :questions

  resources :wizard_steps

  resources :businessplans

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  resources :welcomes

  resources :users

  resources :categories

   root :to => 'welcomes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :featured, :question_id, :user_id

  belongs_to :question
  belongs_to :user

end

app/models/backer.rb
class Backer < ActiveRecord::Base
  attr_accessible :confirmed_at, :finished, :project_id, :user_id, :value, :newsomme

  belongs_to :user
  belongs_to :project
end

app/models/businessplan.rb
class Businessplan < ActiveRecord::Base
  attr_accessible :order, :status, :wizard_answer, :wizard_question, :wizard_step_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :parent, :slug

  	has_many :questions, :foreign_key => :category_id, dependent: :destroy
	has_many :projects, :foreign_key => :category_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug


	has_many :projects, :foreign_key => :location_id, :dependent => :destroy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :challenges, :description, :location_id, :miniature, :category_id, :slug, :title, :video, :user_id, :needs, :somme, :how_know, :facebook_link, :twitter_link, :accepted, :featured, :rejected_for

  belongs_to :user
  belongs_to :location
  belongs_to :category


  has_many :backers, :foreign_key => :project_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :miniature, MiniatureUploader


end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :featured, :is_solved, :question, :slug, :status, :subject, :user_id

  belongs_to :category
  belongs_to :user

  has_many :answers, :foreign_key => :question_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :subject, use: :slugged

end

app/models/startproject.rb
class Startproject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/term.rb
class Term < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :avatar, :biography, :birthday, :birthmonth, :birthyear, :cid, :country_id, :is_coach, :name, :phone, :slug, :state_id, :town, :username, :website, :provider, :uid

  has_many :questions, :foreign_key => :user_id, :dependent => :destroy
  has_many :answers, :foreign_key => :user_id, :dependent => :destroy
  has_many :projects, :foreign_key => :user_id, :dependent => :destroy
  has_many :backers, :foreign_key => :user_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :avatar, AvatarUploader

  acts_as_taggable
  acts_as_taggable_on :skills, :interests


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end



  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end



  
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/wizard_step.rb
class WizardStep < ActiveRecord::Base
  attr_accessible :name, :order

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json

  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/backers_helper.rb
module BackersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_ask_new_question.html.erb
<% if user_signed_in? %>

	<div id="quickquestion">

	  <%= form_for(Question.new(params[:question])) do |f| %>

	    <%= f.text_field :subject, :placeholder => "Le titre de votre question" %>


	      <%= f.text_area :question, :class => "redactor", :value => "Etalez votre sujet d'interrogation ..." %>

	      <%= f.hidden_field :category_id, :value => @category.id %>

	      <%= f.hidden_field :user_id, :value => current_user.id %>

	    <div class="actions">
	      <input name="commit" type="submit" value="Poser la Question" />
	    </div>
	  <% end %>	

	</div>


<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "redactor", :rows => 10, :cols => 60 %>
  </div>
  <div class="field">
    <%= f.label :parent %><br />
    <%= f.number_field :parent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div id="questionslist">
  <% Question.all.each do |question| %>
  <div class="question">
    <%= link_to question.user.name, user_path(question.user) %> asked <%= link_to question.subject, question_path(question) %>
  </div>
  <% end %>
</div>

<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Description</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.slug %></td>
    <td><%= category.description %></td>
    <td><%= category.parent %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="questionscategory">


    <!--<div class="tree">
    	<a href="">Home</a>
    </div>-->
	
	<div class="header">
		<%= @category.name %>
	</div>

	<div class="questionstable">
		<div class="tableheader">
			<div class="question">
				Question
			</div>

			<div class="replies">
				Number of Replies
			</div>

			<div class="byanddate">
				Asked
			</div>
		</div>

		<div class="questions">

			<% Question.where('category_id = ?', @category.id).each do |question| %>
			<div class="question">
				<div class="content">
					<%= link_to question.subject, question_path(question) %>
				</div>

				<div class="replies">
					<%= Answer.where("question_id = ?", question.id).count %>
				</div>

				<div class="byanddate">
					by <%= link_to question.user.username, user_path(question.user) %>
				</div>
			</div>
	  		<% end %>
			
		</div>

	</div>

	<%= render "categories/ask_new_question" %>
</div>