config/routes.rb
Staritup::Application.routes.draw do

  resources :backers

  resources :terms

  resources :policies

  resources :projects

  resources :guidelines

  resources :startprojects

  resources :answers

  resources :questions

  resources :wizard_steps

  resources :businessplans

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  resources :welcomes

  resources :users

  resources :categories

   root :to => 'welcomes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :featured, :question_id, :user_id

  belongs_to :question
  belongs_to :user

end

app/models/backer.rb
class Backer < ActiveRecord::Base
  attr_accessible :confirmed_at, :finished, :project_id, :user_id, :value, :newsomme

  belongs_to :user
  belongs_to :project
end

app/models/businessplan.rb
class Businessplan < ActiveRecord::Base
  attr_accessible :order, :status, :wizard_answer, :wizard_question, :wizard_step_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :parent, :slug

  	has_many :questions, :foreign_key => :category_id, dependent: :destroy
	has_many :projects, :foreign_key => :category_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :country_id, :name, :slug


	has_many :projects, :foreign_key => :location_id, :dependent => :destroy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :challenges, :description, :location_id, :miniature, :category_id, :slug, :title, :video, :user_id, :needs, :somme, :how_know, :facebook_link, :twitter_link, :accepted, :featured, :rejected_for

  belongs_to :user
  belongs_to :location
  belongs_to :category


  has_many :backers, :foreign_key => :project_id, :dependent => :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :miniature, MiniatureUploader


end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :featured, :is_solved, :question, :slug, :status, :subject, :user_id

  belongs_to :category
  belongs_to :user

  has_many :answers, :foreign_key => :question_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :subject, use: :slugged

end

app/models/startproject.rb
class Startproject < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/term.rb
class Term < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :avatar, :biography, :birthday, :birthmonth, :birthyear, :cid, :country_id, :is_coach, :name, :phone, :slug, :state_id, :town, :username, :website, :provider, :uid

  has_many :questions, :foreign_key => :user_id, :dependent => :destroy
  has_many :answers, :foreign_key => :user_id, :dependent => :destroy
  has_many :projects, :foreign_key => :user_id, :dependent => :destroy
  has_many :backers, :foreign_key => :user_id, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :avatar, AvatarUploader

  acts_as_taggable
  acts_as_taggable_on :skills, :interests


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end



  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end



  
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/wizard_step.rb
class WizardStep < ActiveRecord::Base
  attr_accessible :name, :order

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/backers_helper.rb
module BackersHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_announcements.html.erb
_announcements.html.erb

app/views/layouts/_facebook_like.html.erb
<div class="fb-like" data-href="https://www.facebook.com/pages/Staritup/127746127413757" data-send="true" data-layout="box_count" data-width="250" data-show-faces="true"></div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="footercontainer">

    <div class="sitemap">

      <div class="element">
        <div class="big">
          Découvrez
        </div>
        <div class="list">
          <ul>
            <% Category.all.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
            <% end %>
          </ul>
        </div>
      </div>

      
      <div class="element">
        <div class="big">
          Créez
        </div>
        <div class="list">
          <ul>
            <li><%= link_to "Un nouveau Projet", startprojects_path() %></li>
            <li><%= link_to "Une nouvelle Question", questions_path() %></li>
          </ul>
        </div>
      </div>
      
      <div class="element">
        <div class="big">
          Restez Connectés
        </div>
        <div class="list">
          <ul>
            <li><%= link_to "Facebook", "https://www.facebook.com/pages/Staritup/127746127413757" %></li>
            <li><%= link_to "Twitter", "https://twitter.com/staritup1" %></li>
            <li><%= link_to "Google+", "https://plus.google.com/u/0/104364357306788384494/posts" %></li>
            <li><%= link_to "Contact Us", "mailto:contact@staritup.com" %></li>
          </ul>
        </div>
      </div>

      
      <div class="element">
        <div class="big">
          Lisez
        </div>
        <div class="list">
          <ul>
            <li><%= link_to "Termes D'utilisation", terms_path() %></li>
            <li><%= link_to "Contact", "mailto:contact@staritup.com" %></li>
            <li><%= link_to "Politique de Confidencialité", policies_path() %></li>
          </ul>
        </div>
      </div>

    </div>

    <div class="sponsors">

      <div id="footerpartners" class="carousel slide">
        <%= image_tag "partners/globalnet.png" %>
      </div>

    </div>

    <div class="bottommenu">
      <div class="bottomlogo">
        Staritup
      </div>

      <div class="bottomlinks">
        <ul>
          <li>© 2013 MBreath, Inc</li>
        </ul>
      </div>
    </div>
  </div>
</div>
 

app/views/layouts/_header.html.erb
<header>
  <div class="logo">
    <%= link_to (image_tag "logo.png"), root_path() %>
  </div>

  <div class="menu">

    <ul>
      <!-- <li><%= link_to 'Who are we?', 'presentation' %></li>
      <li><%= link_to "Ask for Coaching", categories_path() %></li>-->
      <li><%= link_to "Poser des Questions", questions_path() %></li>
      <li><%= link_to "Découvrir", projects_path() %></li>
      <li><%= link_to "Lancer un Projet", startprojects_path() %></li>
      <li><input type="text" size="30"></li>
    </ul>
    
  </div>

  <div class="personal">

    <ul>
      <% unless user_signed_in? %>
      <li><%= link_to 'Se Connecter', login_path() %></li>
      <li><%= link_to "S'enregistrer", register_path() %></li>
      <% end %>

      <% if user_signed_in? %>
      <li><%= link_to current_user.username, user_path(current_user) %></li>
      <li><%= link_to "Se Deconnecter", logout_path() %></li>
      <% end %>
    </ul>

  </div>
</header>

app/views/layouts/_twitter.html.erb
_twitter.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Staritup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/facebook_sdk" %>

<%= render "layouts/header" %>

<%= yield %>


<%= render "layouts/footer" %>

</body>
</html>